/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import train.ticket.reservation.system.Employee;
import train.ticket.reservation.system.Validation;

/**
 *
 * @author DELL
 */
public class AddEmp extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    public AddEmp() {
        initComponents();
        
        
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        
    }
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jTextFieldSalary = new javax.swing.JTextField();
        jTextFieldQualification = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jPasswordFieldRePass = new javax.swing.JPasswordField();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jPanelNotAllowed = new javax.swing.JPanel();
        jLabelNotAllawed = new javax.swing.JLabel();
        jPanelWrongUserName = new javax.swing.JPanel();
        jLabelWrongUserName1 = new javax.swing.JLabel();
        jPanelWrongPass = new javax.swing.JPanel();
        jLabelWrongPass1 = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabelWrongEmail1 = new javax.swing.JLabel();
        jPanelWrongSalary = new javax.swing.JPanel();
        jLabelWrongSalary1 = new javax.swing.JLabel();
        jPanelWrongQualification = new javax.swing.JPanel();
        jLabelWrongAge1 = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabelWrongPhoneNo1 = new javax.swing.JLabel();
        jPanelWrongID = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jPanelWrongName = new javax.swing.JPanel();
        jLabelWrongName1 = new javax.swing.JLabel();
        jPanelWrongRePass = new javax.swing.JPanel();
        jLabelWrongPass2 = new javax.swing.JLabel();
        jPanelWrongAge = new javax.swing.JPanel();
        jLabelWrongAge = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelProcess = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelReset = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("E-Mail");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Repeat Pass");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone No.");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name");

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salary");

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Qualification");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldName.setBorder(null);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jTextFieldUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserName.setBorder(null);

        jTextFieldEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        jTextFieldAge.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAge.setBorder(null);

        jTextFieldPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNo.setBorder(null);

        jTextFieldSalary.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalary.setBorder(null);
        jTextFieldSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSalaryActionPerformed(evt);
            }
        });

        jTextFieldQualification.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldQualification.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQualification.setBorder(null);
        jTextFieldQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQualificationActionPerformed(evt);
            }
        });

        jPasswordFieldPass.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jPasswordFieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldPass.setBorder(null);
        jPasswordFieldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPassActionPerformed(evt);
            }
        });

        jPasswordFieldRePass.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jPasswordFieldRePass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordFieldRePass.setBorder(null);

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Add New Employee ... !");

        jComboBoxGender.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female"}));

        jPanelNotAllowed.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelNotAllawed.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelNotAllawed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelNotAllawed.setText("Not Allowed");

        javax.swing.GroupLayout jPanelNotAllowedLayout = new javax.swing.GroupLayout(jPanelNotAllowed);
        jPanelNotAllowed.setLayout(jPanelNotAllowedLayout);
        jPanelNotAllowedLayout.setHorizontalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNotAllawed, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
        jPanelNotAllowedLayout.setVerticalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabelNotAllawed)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongUserName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongUserName1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongUserName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongUserName1.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserNameLayout = new javax.swing.GroupLayout(jPanelWrongUserName);
        jPanelWrongUserName.setLayout(jPanelWrongUserNameLayout);
        jPanelWrongUserNameLayout.setHorizontalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongUserName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongUserNameLayout.setVerticalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addComponent(jLabelWrongUserName1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPass.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass1.setText("Wrong Pass");

        javax.swing.GroupLayout jPanelWrongPassLayout = new javax.swing.GroupLayout(jPanelWrongPass);
        jPanelWrongPass.setLayout(jPanelWrongPassLayout);
        jPanelWrongPassLayout.setHorizontalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPassLayout.setVerticalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addComponent(jLabelWrongPass1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongEmail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongEmail1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongEmail1.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addComponent(jLabelWrongEmail1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongSalary.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongSalary1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongSalary1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongSalary1.setText("Wrong Salary");

        javax.swing.GroupLayout jPanelWrongSalaryLayout = new javax.swing.GroupLayout(jPanelWrongSalary);
        jPanelWrongSalary.setLayout(jPanelWrongSalaryLayout);
        jPanelWrongSalaryLayout.setHorizontalGroup(
            jPanelWrongSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongSalary1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongSalaryLayout.setVerticalGroup(
            jPanelWrongSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSalaryLayout.createSequentialGroup()
                .addComponent(jLabelWrongSalary1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongQualification.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAge1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAge1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAge1.setText("Wrong Qualification");

        javax.swing.GroupLayout jPanelWrongQualificationLayout = new javax.swing.GroupLayout(jPanelWrongQualification);
        jPanelWrongQualification.setLayout(jPanelWrongQualificationLayout);
        jPanelWrongQualificationLayout.setHorizontalGroup(
            jPanelWrongQualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQualificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongAge1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongQualificationLayout.setVerticalGroup(
            jPanelWrongQualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQualificationLayout.createSequentialGroup()
                .addComponent(jLabelWrongAge1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPhoneNo.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPhoneNo1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPhoneNo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPhoneNo1.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPhoneNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongPhoneNo1))
        );

        jPanelWrongID.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelID.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabelID)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongName1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongName1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongName1.setText("Wrong Name");

        javax.swing.GroupLayout jPanelWrongNameLayout = new javax.swing.GroupLayout(jPanelWrongName);
        jPanelWrongName.setLayout(jPanelWrongNameLayout);
        jPanelWrongNameLayout.setHorizontalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongName1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongNameLayout.setVerticalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongNameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongName1))
        );

        jPanelWrongRePass.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass2.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass2.setText("Wrong RePass");

        javax.swing.GroupLayout jPanelWrongRePassLayout = new javax.swing.GroupLayout(jPanelWrongRePass);
        jPanelWrongRePass.setLayout(jPanelWrongRePassLayout);
        jPanelWrongRePassLayout.setHorizontalGroup(
            jPanelWrongRePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongRePassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongRePassLayout.setVerticalGroup(
            jPanelWrongRePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongRePassLayout.createSequentialGroup()
                .addComponent(jLabelWrongPass2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongAge.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAge.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAge.setText("Wrong Age");

        javax.swing.GroupLayout jPanelWrongAgeLayout = new javax.swing.GroupLayout(jPanelWrongAge);
        jPanelWrongAge.setLayout(jPanelWrongAgeLayout);
        jPanelWrongAgeLayout.setHorizontalGroup(
            jPanelWrongAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAgeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongAge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongAgeLayout.setVerticalGroup(
            jPanelWrongAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAgeLayout.createSequentialGroup()
                .addComponent(jLabelWrongAge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Reset");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Process");

        jPanelProcess.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Process_96px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelProcessLayout = new javax.swing.GroupLayout(jPanelProcess);
        jPanelProcess.setLayout(jPanelProcessLayout);
        jPanelProcessLayout.setHorizontalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcessLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelProcessLayout.setVerticalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelReset.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelResetLayout = new javax.swing.GroupLayout(jPanelReset);
        jPanelReset.setLayout(jPanelResetLayout);
        jPanelResetLayout.setHorizontalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResetLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13)
                .addGap(0, 0, 0))
        );
        jPanelResetLayout.setVerticalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldRePass, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldQualification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jTextFieldSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelWrongName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongSalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongQualification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongRePass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongRePass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWrongAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jPasswordFieldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPassActionPerformed

    private void jTextFieldQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQualificationActionPerformed
    private void ResetPanel()
    {
        jTextFieldID.setText("");
        jTextFieldAge.setText("");
        jTextFieldEmail.setText("");
        jTextFieldName.setText("");
        jTextFieldPhoneNo.setText("");
        jTextFieldQualification.setText("");
        jTextFieldSalary.setText("");
        jTextFieldUserName.setText("");
        jPasswordFieldPass.setText("");
        jPasswordFieldRePass.setText("");
        jComboBoxGender.setSelectedIndex(0);
        
        
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        
    }
    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongRePass.setVisible(false);
        
        if(!jTextFieldID.getText().equals("") && !jTextFieldName.getText().equals("") && !jTextFieldUserName.getText().equals("") && !jPasswordFieldPass.getText().equals("") && !jPasswordFieldRePass.getText().equals("") && !jTextFieldEmail.getText().equals("") && !jTextFieldAge.getText().equals("") && !jTextFieldPhoneNo.getText().equals("") && !jTextFieldSalary.getText().equals("") && !jTextFieldQualification.getText().equals(""))
        {
            //All Check ...
            Validation v = new Validation();
            if(v.checkID(jTextFieldID.getText())){
                if(v.checkName(jTextFieldName.getText())){
                    if(v.checkName(jTextFieldUserName.getText())){
                        if(v.checkPass(jPasswordFieldPass.getText())){
                            if(v.checkPass(jPasswordFieldRePass.getText())){
                                if(v.checkEmail(jTextFieldEmail.getText())){
                                    if(v.checkAge(jTextFieldAge.getText())){
                                        if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                            if(v.checkSalary(jTextFieldSalary.getText())){
                                                if(v.checkName(jTextFieldQualification.getText())){
                                                    // End Check :)
                                                    // Start Add
                                                        Employee e = new Employee();
                                                        if(!e.Dublicate(Integer.parseInt(jTextFieldID.getText()))){
                                                            e.SetID(Integer.parseInt(jTextFieldID.getText()));
                                                            e.SetName(jTextFieldName.getText());
                                                            e.SetUsername(jTextFieldUserName.getText());
                                                            e.SetEmail(jTextFieldEmail.getText());
                                                            e.SetAge(Integer.parseInt(jTextFieldAge.getText()));
                                                            e.SetPhoneNo(jTextFieldPhoneNo.getText());
                                                            e.SetSalary(Double.parseDouble(jTextFieldSalary.getText()));
                                                            e.SetQualification(jTextFieldQualification.getText());
                                                            e.SetGender(jComboBoxGender.getSelectedItem().toString());
                                                            if(jPasswordFieldPass.getText().equals(jPasswordFieldRePass.getText())){
                                                                e.SetPassword(jPasswordFieldPass.getText());
                                                                    if(e.AddEmployee()){
                                                                        jLabelSuccessOrFail.setText("Added Successfull ... ! :)");
                                                                        ResetPanel();
                                                                    }
                                                                    else
                                                                        jLabelSuccessOrFail.setText("Failed To Insert ... !");
                                                                 }
                                                                 else{
                                                                jLabelSuccessOrFail.setText("Password & Repassword not Similar ... ! :("); 
                                                                JOptionPane.showMessageDialog(null, "Not valid Password & Repassword not Similar Try Again :(");
                                                                jPanelWrongPass.setVisible(true); jPanelWrongRePass.setVisible(true);
                                                             }
                                                            //End Start & start elses for Check
                                                        }
                                                            else{
                                                                    jLabelSuccessOrFail.setText("Not Allowed New ID Employee :(");
                                                                    jPanelNotAllowed.setVisible(true);
                                                                    JOptionPane.showMessageDialog(null, "Not Allowed ID Employee , ID Employee is Reserved...!\n Try Again :(");
                                                        }
                                            }
                                            else{
                                                    JOptionPane.showMessageDialog(null, "Not valid Input for Qualification Try Again :(");
                                                    jPanelWrongQualification.setVisible(true);
                                            }
                                        }
                                            else{
                                                JOptionPane.showMessageDialog(null, "Not valid Salary Try Again :(\nHint: Salary should more than 1000 .. ;)");
                                                jPanelWrongSalary.setVisible(true);
                                            }
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                            jPanelWrongPhoneNo.setVisible(true);
                                        }
                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null, "Not valid Age Try Again :(\nHint: Age should more than 18 .. ;)");
                                        jPanelWrongAge.setVisible(true);
                                    }
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                    jPanelWrongEmail.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid RePassword length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                jPanelWrongRePass.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                            jPanelWrongPass.setVisible(true);
                        }
                }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :(");
                        jPanelWrongUserName.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                    jPanelWrongName.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                jPanelWrongID.setVisible(true);
            }
            
        }
        else
            jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        setColor(jPanelProcess);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        // TODO add your handling code here:
        getColor(jPanelProcess);
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        ResetPanel();
        jLabelSuccessOrFail.setText("Add New Employee ... !");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        setColor(jPanelReset);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        getColor(jPanelReset);
    }//GEN-LAST:event_jLabel13MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNotAllawed;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWrongAge;
    private javax.swing.JLabel jLabelWrongAge1;
    private javax.swing.JLabel jLabelWrongEmail1;
    private javax.swing.JLabel jLabelWrongName1;
    private javax.swing.JLabel jLabelWrongPass1;
    private javax.swing.JLabel jLabelWrongPass2;
    private javax.swing.JLabel jLabelWrongPhoneNo1;
    private javax.swing.JLabel jLabelWrongSalary1;
    private javax.swing.JLabel jLabelWrongUserName1;
    private javax.swing.JPanel jPanelNotAllowed;
    private javax.swing.JPanel jPanelProcess;
    private javax.swing.JPanel jPanelReset;
    private javax.swing.JPanel jPanelWrongAge;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongName;
    private javax.swing.JPanel jPanelWrongPass;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongQualification;
    private javax.swing.JPanel jPanelWrongRePass;
    private javax.swing.JPanel jPanelWrongSalary;
    private javax.swing.JPanel jPanelWrongUserName;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JPasswordField jPasswordFieldRePass;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldQualification;
    private javax.swing.JTextField jTextFieldSalary;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
