/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import train.ticket.reservation.system.Ticket;

/**
 *
 * @author DELL
 */
public class ListAllTicket extends javax.swing.JPanel {

    /**
     * Creates new form ListAllTicket
     */
    public ListAllTicket() {
        initComponents();
        //AddRowToJTable();
    }
    public void AddRowToJTable()
    {
        resetTable();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object []rowData = new Object[9];
        ArrayList<Ticket> tikets = new ArrayList<Ticket>();
        Ticket x = new Ticket();
        tikets = x.ListTicket();
        
        for(Ticket t : tikets){
            rowData[0]=t.GetName();
            rowData[1]=t.GetIDTicket();
            rowData[2]=t.GetPhoneNo();
            rowData[3]=t.getLine();
            rowData[4]=t.GetSource();
            rowData[5]=t.GetDistantion();
            rowData[6]=t.PriceOFTicket(t.getLine(),t.GetSource(), t.GetDistantion());
            rowData[7]=t.GetEmail();
            String Sepreted[]=t.getDate().split("#");
            Sepreted[0]=String.valueOf(Integer.parseInt(Sepreted[0])+2000);
            rowData[8]=Sepreted[0]+"/"+Sepreted[1]+"/"+Sepreted[2]+"   |   "+Sepreted[3]+":"+Sepreted[4];
            model.addRow(rowData);
        }
    }private void resetTable()
     {
         try{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            while(jTable1.getRowCount()>0){
                for(int i=0;i<jTable1.getRowCount();i++)
                    model.removeRow(i);
            }
            model.removeRow(0);
        }
        catch(Exception e)
        {
            ;
        }
     }
    
            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Monotype Corsiva", 0, 16)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger", "ID Ticket", "Phone No", "Line", "Source", "Distination", "Salary", "E-Mail", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
