/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import train.ticket.reservation.system.Employee;
import train.ticket.reservation.system.Validation;

/**
 *
 * @author DELL
 */
public class SearchEmp extends javax.swing.JPanel {

    /**
     * Creates new form SearchEmployee
     */
    public SearchEmp() {
        initComponents();
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongIDEmployee.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSearchIDEmployee = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldUserName = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldSalary = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldQualification = new javax.swing.JTextField();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jSeparator10 = new javax.swing.JSeparator();
        jPanelWrongID = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jPanelNotAllowed = new javax.swing.JPanel();
        jLabelNotAllawed = new javax.swing.JLabel();
        jPanelWrongName = new javax.swing.JPanel();
        jLabelWrongName = new javax.swing.JLabel();
        jPanelWrongUserName = new javax.swing.JPanel();
        jLabelWrongUserName = new javax.swing.JLabel();
        jPanelWrongPass = new javax.swing.JPanel();
        jLabelWrongPass = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabelWrongEmail = new javax.swing.JLabel();
        jPanelWrongSalary = new javax.swing.JPanel();
        jLabelWrongSalary = new javax.swing.JLabel();
        jPanelWrongQualification = new javax.swing.JPanel();
        jLabelWrongQualification = new javax.swing.JLabel();
        jPanelWrongAge = new javax.swing.JPanel();
        jLabelWrongAge = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabelWrongPhoneNo = new javax.swing.JLabel();
        jPanelWrongIDEmployee = new javax.swing.JPanel();
        jLabelID1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelReset = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelDelete = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jTextFieldSearchIDEmployee.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldSearchIDEmployee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSearchIDEmployee.setBorder(null);
        jTextFieldSearchIDEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchIDEmployeeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User Name");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-Mail");

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Salary");

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Qualification");

        jTextFieldName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldName.setBorder(null);

        jTextFieldUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUserName.setBorder(null);

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jTextFieldSalary.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldSalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalary.setBorder(null);

        jTextFieldEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setBorder(null);

        jTextFieldQualification.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldQualification.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldQualification.setBorder(null);
        jTextFieldQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQualificationActionPerformed(evt);
            }
        });

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search For Employee ... !");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Employee");

        jTextFieldPass.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPass.setBorder(null);

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gender");

        jTextFieldPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNo.setBorder(null);

        jTextFieldAge.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAge.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone No.");

        jComboBoxGender.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male" , "Famele"}));
        jComboBoxGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGenderActionPerformed(evt);
            }
        });

        jPanelWrongID.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelID.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabelID)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelNotAllowed.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelNotAllawed.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelNotAllawed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelNotAllawed.setText("Not Allowed");

        javax.swing.GroupLayout jPanelNotAllowedLayout = new javax.swing.GroupLayout(jPanelNotAllowed);
        jPanelNotAllowed.setLayout(jPanelNotAllowedLayout);
        jPanelNotAllowedLayout.setHorizontalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNotAllawed, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
        jPanelNotAllowedLayout.setVerticalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabelNotAllawed)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongName.setText("Wrong Name");

        javax.swing.GroupLayout jPanelWrongNameLayout = new javax.swing.GroupLayout(jPanelWrongName);
        jPanelWrongName.setLayout(jPanelWrongNameLayout);
        jPanelWrongNameLayout.setHorizontalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongNameLayout.setVerticalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongNameLayout.createSequentialGroup()
                .addComponent(jLabelWrongName)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongUserName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongUserName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongUserName.setText("Wrong User Name");

        javax.swing.GroupLayout jPanelWrongUserNameLayout = new javax.swing.GroupLayout(jPanelWrongUserName);
        jPanelWrongUserName.setLayout(jPanelWrongUserNameLayout);
        jPanelWrongUserNameLayout.setHorizontalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
        );
        jPanelWrongUserNameLayout.setVerticalGroup(
            jPanelWrongUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongUserNameLayout.createSequentialGroup()
                .addComponent(jLabelWrongUserName)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPass.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPass.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPass.setText("Wrong Pass");

        javax.swing.GroupLayout jPanelWrongPassLayout = new javax.swing.GroupLayout(jPanelWrongPass);
        jPanelWrongPass.setLayout(jPanelWrongPassLayout);
        jPanelWrongPassLayout.setHorizontalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPassLayout.setVerticalGroup(
            jPanelWrongPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPassLayout.createSequentialGroup()
                .addComponent(jLabelWrongPass)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongEmail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongEmail.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongEmail))
        );

        jPanelWrongSalary.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongSalary.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongSalary.setText("Wrong Salary");

        javax.swing.GroupLayout jPanelWrongSalaryLayout = new javax.swing.GroupLayout(jPanelWrongSalary);
        jPanelWrongSalary.setLayout(jPanelWrongSalaryLayout);
        jPanelWrongSalaryLayout.setHorizontalGroup(
            jPanelWrongSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSalaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongSalary)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelWrongSalaryLayout.setVerticalGroup(
            jPanelWrongSalaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSalaryLayout.createSequentialGroup()
                .addComponent(jLabelWrongSalary)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongQualification.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongQualification.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongQualification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongQualification.setText("Wrong Qualification");

        javax.swing.GroupLayout jPanelWrongQualificationLayout = new javax.swing.GroupLayout(jPanelWrongQualification);
        jPanelWrongQualification.setLayout(jPanelWrongQualificationLayout);
        jPanelWrongQualificationLayout.setHorizontalGroup(
            jPanelWrongQualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQualificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongQualification)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongQualificationLayout.setVerticalGroup(
            jPanelWrongQualificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongQualificationLayout.createSequentialGroup()
                .addComponent(jLabelWrongQualification)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongAge.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongAge.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongAge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongAge.setText("Wrong Age");

        javax.swing.GroupLayout jPanelWrongAgeLayout = new javax.swing.GroupLayout(jPanelWrongAge);
        jPanelWrongAge.setLayout(jPanelWrongAgeLayout);
        jPanelWrongAgeLayout.setHorizontalGroup(
            jPanelWrongAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAgeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongAge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelWrongAgeLayout.setVerticalGroup(
            jPanelWrongAgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongAgeLayout.createSequentialGroup()
                .addComponent(jLabelWrongAge)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPhoneNo.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPhoneNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPhoneNo.setText("Wrong Phone No");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPhoneNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addComponent(jLabelWrongPhoneNo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongIDEmployee.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelID1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelID1.setText("Wrong Search Key");

        javax.swing.GroupLayout jPanelWrongIDEmployeeLayout = new javax.swing.GroupLayout(jPanelWrongIDEmployee);
        jPanelWrongIDEmployee.setLayout(jPanelWrongIDEmployeeLayout);
        jPanelWrongIDEmployeeLayout.setHorizontalGroup(
            jPanelWrongIDEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        );
        jPanelWrongIDEmployeeLayout.setVerticalGroup(
            jPanelWrongIDEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDEmployeeLayout.createSequentialGroup()
                .addComponent(jLabelID1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reset");

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Search");

        jPanel1.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelSearch.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_96px.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Update Employee");

        jLabel22.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Remove Employee");

        jPanelDelete.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Delete_Shield_96px_1.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelDeleteLayout = new javax.swing.GroupLayout(jPanelDelete);
        jPanelDelete.setLayout(jPanelDeleteLayout);
        jPanelDeleteLayout.setHorizontalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDeleteLayout.setVerticalGroup(
            jPanelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDeleteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_96px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldID)
                            .addComponent(jTextFieldUserName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFieldPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFieldQualification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFieldSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jTextFieldAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanelWrongPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelWrongName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanelWrongSalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongQualification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jSeparator10)
                                            .addComponent(jTextFieldSearchIDEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelWrongIDEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSearchIDEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jPanelWrongIDEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelWrongUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelWrongPass, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWrongQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWrongAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchIDEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchIDEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchIDEmployeeActionPerformed
    
    private void setPanel(Employee a)
    {
        jTextFieldID.setText(""+a.GetID());
        jTextFieldName.setText(""+a.GetName());
        jTextFieldQualification.setText(""+a.GetQualification());
        jTextFieldSalary.setText(""+a.GetSalary());
        jTextFieldUserName.setText(""+a.GetUsername());
        jTextFieldEmail.setText(""+a.GetEmail());
        jTextFieldPass.setText(""+a.GetPassword());
        jTextFieldAge.setText(""+a.GetAge());
        jComboBoxGender.setSelectedItem(a.GetGender());
        jTextFieldPhoneNo.setText(""+a.GetPhoneNo());
    }
    private void ResetPanel()
    {
        jTextFieldID.setText("");
        jTextFieldName.setText("");
        jTextFieldPass.setText("");
        jTextFieldUserName.setText("");
        jTextFieldEmail.setText("");
        jTextFieldSalary.setText("");
        jTextFieldQualification.setText("");
        jTextFieldSearchIDEmployee.setText("");
        jTextFieldAge.setText("");
        jComboBoxGender.setSelectedIndex(0);
        jTextFieldPhoneNo.setText("");
        jTextFieldSearchIDEmployee.setText("");
        
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongIDEmployee.setVisible(false);
        
    }
    
    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jComboBoxGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGenderActionPerformed

    private void jTextFieldQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQualificationActionPerformed

    private void jLabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseClicked
        // TODO add your handling code here:
        ResetPanel();
        jLabelSuccessOrFail.setText("Search For Employee ... !");
    }//GEN-LAST:event_jLabelResetMouseClicked

    private void jLabelResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabelResetMouseEntered

    private void jLabelResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabelResetMouseExited

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        // TODO add your handling code here:
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongIDEmployee.setVisible(false);
        
        if(!jTextFieldSearchIDEmployee.getText().equals("")){
            if(new Validation().checkID(jTextFieldSearchIDEmployee.getText())){
                Employee emp = new Employee();
                Employee x = emp.getEmp(Integer.parseInt(jTextFieldSearchIDEmployee.getText()));
                if(x!=null && x.GetID()>0){
                    setPanel(x);
                    jLabelSuccessOrFail.setText("Founded ...! :) ");

                }
                else{
                    jLabelSuccessOrFail.setText("Not Found ...! :(");
                    JOptionPane.showMessageDialog(null, "Not Found ID Employee ...!\n Try Again :(");
                    ResetPanel();
                }
            }
            else{
                jLabelSuccessOrFail.setText("Not valid ID Search for Employee :( ");
                JOptionPane.showMessageDialog(null, "Not valid ID Employee Try Again :(\nHint: ID Employee Length should more than 4 .. ;)");
                jPanelWrongIDEmployee.setVisible(true);
            }
        }
        else{
            jLabelSuccessOrFail.setText("Missing Required Fields ... ! Please Fill All Fields :(");
            ResetPanel();
        }
    }//GEN-LAST:event_jLabelSearchMouseClicked
private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    private void jLabelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jLabelSearchMouseEntered

    private void jLabelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jLabelSearchMouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        jPanelWrongIDEmployee.setVisible(false);
        
        if(!jTextFieldSearchIDEmployee.getText().equals(""))
        {
            Employee emp = new Employee();
            if(emp.RemoveEmployee(Integer.parseInt(jTextFieldSearchIDEmployee.getText())))
            {
                jLabelSuccessOrFail.setText("Deleted Successfully ...! :)");
                ResetPanel();
            }
            else{
                jLabelSuccessOrFail.setText("Not Found ...! :(");
                JOptionPane.showMessageDialog(null, "Not Found ID Employee ,Failed Delete ...!\n Try Again :(");
                ResetPanel();
            }            
        }
        else
            jLabelSuccessOrFail.setText("Missing Required Fields ... ! Please Fill All Fields :(");
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jPanelDelete.setBackground(Color.red);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
        getColor(jPanelDelete);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jPanelWrongAge.setVisible(false);
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPass.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongQualification.setVisible(false);
        jPanelWrongSalary.setVisible(false);
        jPanelWrongUserName.setVisible(false);
        jPanelWrongIDEmployee.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        
        if(!jTextFieldID.getText().equals("") && !jTextFieldName.getText().equals("") && !jTextFieldPass.getText().equals("") && !jTextFieldQualification.getText().equals("") && !jTextFieldSalary.getText().equals("") && !jTextFieldUserName.getText().equals("") && !jTextFieldEmail.getText().equals("") && !jTextFieldAge.getText().equals("")  && !jTextFieldSalary.getText().equals("") )
        {
            //All Check ...
            Validation v = new Validation();
                if(v.checkID(jTextFieldSearchIDEmployee.getText())){
                if(v.checkID(jTextFieldID.getText())){
                    if(v.checkName(jTextFieldName.getText())){
                        if(v.checkName(jTextFieldUserName.getText())){
                            if(v.checkPass(jTextFieldPass.getText())){
                                    if(v.checkEmail(jTextFieldEmail.getText())){
                                        if(v.checkAge(jTextFieldAge.getText())){
                                            if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                                                if(v.checkSalary(jTextFieldSalary.getText())){
                                                    if(v.checkName(jTextFieldQualification.getText())){
                                                        // End Check :)
                                                        // Start Add
                                                        Employee x = new Employee();
                                                        if(!jTextFieldID.getText().equals(jTextFieldSearchIDEmployee.getText())){
                                                            if(!x.Dublicate(Integer.parseInt(jTextFieldID.getText()))){
                                                                x.SetAge(Integer.parseInt(jTextFieldAge.getText()));
                                                                x.SetEmail(jTextFieldEmail.getText());
                                                                x.SetGender(jComboBoxGender.getSelectedItem().toString());
                                                                x.SetID(Integer.parseInt(jTextFieldID.getText()));
                                                                x.SetName(jTextFieldName.getText());
                                                                x.SetPassword(jTextFieldPass.getText());
                                                                x.SetPhoneNo(jTextFieldPhoneNo.getText());
                                                                x.SetQualification(jTextFieldQualification.getText());
                                                                x.SetSalary(Double.parseDouble(jTextFieldSalary.getText()));
                                                                x.SetUsername(jTextFieldUserName.getText());
                                                                    if(x.EditInEmployee(Integer.parseInt(jTextFieldSearchIDEmployee.getText()))){
                                                                        ResetPanel();
                                                                        jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                                    }
                                                                    else{
                                                                        jLabelSuccessOrFail.setText("Failed Updated ...! :("); 
                                                                        JOptionPane.showMessageDialog(null, "Failed Updated ...! :(");
                                                                        ResetPanel();
                                                                    }
                                                                    //End Start & start elses for Check
                                                                 }
                                                            else{
                                                                    jLabelSuccessOrFail.setText("Not Allowed New ID Employee :(");
                                                                    jPanelNotAllowed.setVisible(true);
                                                                    JOptionPane.showMessageDialog(null, "Not Allowed ID Employee , ID Employee is Reserved...!\n Try Again :(");
                                                            }
                                                        }
                                                        else{
                                                            x.SetAge(Integer.parseInt(jTextFieldAge.getText()));
                                                                x.SetEmail(jTextFieldEmail.getText());
                                                                x.SetGender(jComboBoxGender.getSelectedItem().toString());
                                                                x.SetID(Integer.parseInt(jTextFieldID.getText()));
                                                                x.SetName(jTextFieldName.getText());
                                                                x.SetPassword(jTextFieldPass.getText());
                                                                x.SetPhoneNo(jTextFieldPhoneNo.getText());
                                                                x.SetQualification(jTextFieldQualification.getText());
                                                                x.SetSalary(Double.parseDouble(jTextFieldSalary.getText()));
                                                                x.SetUsername(jTextFieldUserName.getText());
                                                                    if(x.EditInEmployee(Integer.parseInt(jTextFieldSearchIDEmployee.getText()))){
                                                                        ResetPanel();
                                                                        jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                                    }
                                                                    else{
                                                                        jLabelSuccessOrFail.setText("Failed Updated ...! :("); 
                                                                        JOptionPane.showMessageDialog(null, "Failed Updated ...! :(");
                                                                        ResetPanel();
                                                                    }
                                                                    //End Start & start elses for Check
                                                        }
                                                }
                                                else{
                                                        JOptionPane.showMessageDialog(null, "Not valid Input for Qualification Try Again :(");
                                                        jPanelWrongQualification.setVisible(true);
                                                }
                                            }
                                                else{
                                                    JOptionPane.showMessageDialog(null, "Not valid Salary Try Again :(\nHint: Salary should more than 1000 .. ;)");
                                                    jPanelWrongSalary.setVisible(true);
                                                }
                                            }
                                            else{
                                                JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                                                jPanelWrongPhoneNo.setVisible(true);
                                            }
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null, "Not valid Age Try Again :(\nHint: Age should more than 18 .. ;)");
                                            jPanelWrongAge.setVisible(true);
                                        }
                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                        jPanelWrongEmail.setVisible(true);
                                    }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid Password length ,Should it Length\nis more than 6 OR Password has (*,/,=,+,...)\n                    Try Again :(");
                                jPanelWrongPass.setVisible(true);
                            }
                    }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid User Name Try Again :(");
                            jPanelWrongUserName.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                        jPanelWrongName.setVisible(true);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid ID Try Again :(\nHint: ID Length should more than 4 .. ;)");
                    jPanelWrongID.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Employee Try Again :(\nHint: ID Employee Length should more than 4 .. ;)");
                jPanelWrongIDEmployee.setVisible(true);
            }
        }
        else
            jLabelSuccessOrFail.setText("Missing Required ID Employee ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(Color.green);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabel18MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelNotAllawed;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWrongAge;
    private javax.swing.JLabel jLabelWrongEmail;
    private javax.swing.JLabel jLabelWrongName;
    private javax.swing.JLabel jLabelWrongPass;
    private javax.swing.JLabel jLabelWrongPhoneNo;
    private javax.swing.JLabel jLabelWrongQualification;
    private javax.swing.JLabel jLabelWrongSalary;
    private javax.swing.JLabel jLabelWrongUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDelete;
    private javax.swing.JPanel jPanelNotAllowed;
    private javax.swing.JPanel jPanelWrongAge;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongIDEmployee;
    private javax.swing.JPanel jPanelWrongName;
    private javax.swing.JPanel jPanelWrongPass;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JPanel jPanelWrongQualification;
    private javax.swing.JPanel jPanelWrongSalary;
    private javax.swing.JPanel jPanelWrongUserName;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPass;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldQualification;
    private javax.swing.JTextField jTextFieldSalary;
    private javax.swing.JTextField jTextFieldSearchIDEmployee;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
