/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.Panels;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import train.ticket.reservation.system.Mail;
import train.ticket.reservation.system.Ticket;
import train.ticket.reservation.system.Validation;

/**
 *
 * @author DELL
 */
public class ServeTicket extends javax.swing.JPanel {

    /**
     * Creates new form ServeTicket
     */
    public ServeTicket() {
        initComponents();
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongIDTicket.setVisible(false);
        
        jPanelNotAllowed.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jTextFieldIDTicket = new javax.swing.JTextField();
        jTextFieldPassenger = new javax.swing.JTextField();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxSelectLine = new javax.swing.JComboBox<>();
        jComboBoxSource = new javax.swing.JComboBox<>();
        jComboBoxDistination = new javax.swing.JComboBox<>();
        jComboBoxHour = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox<>();
        jComboBoxminute = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxyear = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxmonth = new javax.swing.JComboBox<>();
        jPanelWrongID = new javax.swing.JPanel();
        jLabelWrongID = new javax.swing.JLabel();
        jPanelWrongName = new javax.swing.JPanel();
        jLabelWrongName = new javax.swing.JLabel();
        jPanelWrongPhoneNo = new javax.swing.JPanel();
        jLabelWrongPhoneNo = new javax.swing.JLabel();
        jPanelWrongIDTicket = new javax.swing.JPanel();
        jLabelWrongIDTicket = new javax.swing.JLabel();
        jPanelWrongEmail = new javax.swing.JPanel();
        jLabelWrongEmail = new javax.swing.JLabel();
        jPanelNotAllowed = new javax.swing.JPanel();
        jLabelWrongID1 = new javax.swing.JLabel();
        jPanelReset = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMail = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanelProcess = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name Of Passenger");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No.");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Ticket");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Source");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-Mail");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Price");

        jTextFieldPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPhoneNo.setBorder(null);

        jTextFieldIDTicket.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldIDTicket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIDTicket.setBorder(null);
        jTextFieldIDTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDTicketActionPerformed(evt);
            }
        });

        jTextFieldPassenger.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldPassenger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPassenger.setBorder(null);
        jTextFieldPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPassengerActionPerformed(evt);
            }
        });

        jTextFieldPrice.setEditable(false);
        jTextFieldPrice.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Distination");

        jTextFieldemail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldemail.setBorder(null);
        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Add Passenger ... !");

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Passenger");

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Line");

        jComboBoxSelectLine.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxSelectLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Line 1","Line 2","Line 3"}));
        jComboBoxSelectLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSelectLineActionPerformed(evt);
            }
        });

        jComboBoxSource.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"El Shohadaa","Ahmed Orabi","Naser","Saddat","Saad Zaghlol","El Sayeda Zeinb","El Malk El Saled","Mari Gargis","El Zahraa","Dar El Salam","Haddayk El Maadi","El Maadi","Thakant El Maadi","Tora El Balad","Kozzika","Tora Al-Asmant","El Maasara","Hadayaa Helwan","Wadi Hoof","Helwan University","Ain Helwan","Helwan"}));
        jComboBoxSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSourceActionPerformed(evt);
            }
        });

        jComboBoxDistination.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxDistination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"El Shohadaa","Ahmed Orabi","Naser","Saddat","Saad Zaghlol","El Sayeda Zeinb","El Malk El Saled","Mari Gargis","El Zahraa","Dar El Salam","Haddayk El Maadi","El Maadi","Thakant El Maadi","Tora El Balad","Kozzika","Tora Al-Asmant","El Maasara","Hadayaa Helwan","Wadi Hoof","Helwan University","Ain Helwan","Helwan"}));
        jComboBoxDistination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDistinationActionPerformed(evt);
            }
        });

        jComboBoxHour.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxHour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","00" }));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");

        jComboBoxday.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));

        jComboBoxminute.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxminute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60" }));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Year");

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Month");

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Day");

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hour");

        jComboBoxyear.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18" , "19" , "21" , "22" }));
        jComboBoxyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxyearActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Minute");

        jComboBoxmonth.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12" }));

        jPanelWrongID.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongID.setText("Wrong ID");

        javax.swing.GroupLayout jPanelWrongIDLayout = new javax.swing.GroupLayout(jPanelWrongID);
        jPanelWrongID.setLayout(jPanelWrongIDLayout);
        jPanelWrongIDLayout.setHorizontalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongIDLayout.setVerticalGroup(
            jPanelWrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDLayout.createSequentialGroup()
                .addComponent(jLabelWrongID)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongName.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongName.setText("Wrong Name ");

        javax.swing.GroupLayout jPanelWrongNameLayout = new javax.swing.GroupLayout(jPanelWrongName);
        jPanelWrongName.setLayout(jPanelWrongNameLayout);
        jPanelWrongNameLayout.setHorizontalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongNameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelWrongName)
                .addContainerGap())
        );
        jPanelWrongNameLayout.setVerticalGroup(
            jPanelWrongNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongNameLayout.createSequentialGroup()
                .addComponent(jLabelWrongName)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongPhoneNo.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongPhoneNo.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelWrongPhoneNo.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongPhoneNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongPhoneNo.setText("Wrong Phone NO");

        javax.swing.GroupLayout jPanelWrongPhoneNoLayout = new javax.swing.GroupLayout(jPanelWrongPhoneNo);
        jPanelWrongPhoneNo.setLayout(jPanelWrongPhoneNoLayout);
        jPanelWrongPhoneNoLayout.setHorizontalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongPhoneNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongPhoneNoLayout.setVerticalGroup(
            jPanelWrongPhoneNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongPhoneNoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelWrongPhoneNo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongIDTicket.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongIDTicket.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongIDTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongIDTicket.setText("Wrong ID Ticket");

        javax.swing.GroupLayout jPanelWrongIDTicketLayout = new javax.swing.GroupLayout(jPanelWrongIDTicket);
        jPanelWrongIDTicket.setLayout(jPanelWrongIDTicketLayout);
        jPanelWrongIDTicketLayout.setHorizontalGroup(
            jPanelWrongIDTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongIDTicket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWrongIDTicketLayout.setVerticalGroup(
            jPanelWrongIDTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongIDTicketLayout.createSequentialGroup()
                .addComponent(jLabelWrongIDTicket)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelWrongEmail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongEmail.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongEmail.setText("Wrong E-Mail");

        javax.swing.GroupLayout jPanelWrongEmailLayout = new javax.swing.GroupLayout(jPanelWrongEmail);
        jPanelWrongEmail.setLayout(jPanelWrongEmailLayout);
        jPanelWrongEmailLayout.setHorizontalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );
        jPanelWrongEmailLayout.setVerticalGroup(
            jPanelWrongEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongEmailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelWrongEmail))
        );

        jPanelNotAllowed.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelWrongID1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabelWrongID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabelWrongID1.setText("Not Allowed");

        javax.swing.GroupLayout jPanelNotAllowedLayout = new javax.swing.GroupLayout(jPanelNotAllowed);
        jPanelNotAllowed.setLayout(jPanelNotAllowedLayout);
        jPanelNotAllowedLayout.setHorizontalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWrongID1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNotAllowedLayout.setVerticalGroup(
            jPanelNotAllowedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNotAllowedLayout.createSequentialGroup()
                .addComponent(jLabelWrongID1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelReset.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelResetLayout = new javax.swing.GroupLayout(jPanelReset);
        jPanelReset.setLayout(jPanelResetLayout);
        jPanelResetLayout.setHorizontalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResetLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );
        jPanelResetLayout.setVerticalGroup(
            jPanelResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelMail.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Send_Email_96px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelMailLayout = new javax.swing.GroupLayout(jPanelMail);
        jPanelMail.setLayout(jPanelMailLayout);
        jPanelMailLayout.setHorizontalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMailLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMailLayout.setVerticalGroup(
            jPanelMailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jPanelProcess.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Process_96px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelProcessLayout = new javax.swing.GroupLayout(jPanelProcess);
        jPanelProcess.setLayout(jPanelProcessLayout);
        jPanelProcessLayout.setHorizontalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProcessLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelProcessLayout.setVerticalGroup(
            jPanelProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Process & Send Mail");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Process");

        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxSelectLine, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxSource, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldIDTicket, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jComboBoxDistination, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanelWrongIDTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxminute, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabelSuccessOrFail)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelWrongPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldIDTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelNotAllowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSelectLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDistination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelWrongIDTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelWrongEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxyear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(2, 2, 2)
                            .addComponent(jComboBoxmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxminute, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPassengerActionPerformed
    
    private void ResetPanel()
    {
        jComboBoxSelectLine.setSelectedIndex(0);
        jComboBoxSource.setSelectedIndex(0);
        jComboBoxDistination.setSelectedIndex(0);
        jTextFieldID.setText("");
        jTextFieldIDTicket.setText("");
        jTextFieldPassenger.setText("");
        jTextFieldPhoneNo.setText("");
        jTextFieldemail.setText("");
        jComboBoxHour.setSelectedIndex(0);
        jComboBoxday.setSelectedIndex(0);
        jComboBoxyear.setSelectedIndex(0);
        jComboBoxmonth.setSelectedIndex(0);
        jComboBoxminute.setSelectedIndex(0);
        
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongIDTicket.setVisible(false);
        
    }
    
    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jTextFieldIDTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDTicketActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jComboBoxSelectLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSelectLineActionPerformed
        // TODO add your handling code here:
        if(jComboBoxSelectLine.getSelectedItem().equals("Line 1")){
                jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"El Shohadaa","Ahmed Orabi","Naser","Saddat","Saad Zaghlol","El Sayeda Zeinb","El Malk El Saled","Mari Gargis","El Zahraa","Dar El Salam","Haddayk El Maadi","El Maadi","Thakant El Maadi","Tora El Balad","Kozzika","Tora Al-Asmant","El Maasara","Hadayaa Helwan","Wadi Hoof","Helwan University","Ain Helwan","Helwan"}));
                jComboBoxDistination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"El Shohadaa","Ahmed Orabi","Naser","Saddat","Saad Zaghlol","El Sayeda Zeinb","El Malk El Saled","Mari Gargis","El Zahraa","Dar El Salam","Haddayk El Maadi","El Maadi","Thakant El Maadi","Tora El Balad","Kozzika","Tora Al-Asmant","El Maasara","Hadayaa Helwan","Wadi Hoof","Helwan University","Ain Helwan","Helwan"}));
         }
        else if(jComboBoxSelectLine.getSelectedItem().equals("Line 2")){
                jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Shubra","Koleyet El Zeraat","El Mazallat","El Khalafawi","St. Teresa","Rod El Farag","Massara","El Shohadaa","Atatba","M.Naguib","Saddat","Dokki","El Bohoos","Cairo University","Faysal","Giza","Omm El Misryeen","Sakiat Mekki","El Monib"}));
                jComboBoxDistination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Shubra","Koleyet El Zeraat","El Mazallat","El Khalafawi","St. Teresa","Rod El Farag","Massara","El Shohadaa","Atatba","M.Naguib","Saddat","Dokki","El Bohoos","Cairo University","Faysal","Giza","Omm El Misryeen","Sakiat Mekki","El Monib"}));
        }
         else if(jComboBoxSelectLine.getSelectedItem().equals("Line 3")){
                jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Al Ahram","Koleyet El Banat","Cairo Stadium","Cairo Fairgrounds","Abbassiya","Abdou Pasha","El Geish","Bab El Shaaria","Atatba"}));
                jComboBoxDistination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Al Ahram","Koleyet El Banat","Cairo Stadium","Cairo Fairgrounds","Abbassiya","Abdou Pasha","El Geish","Bab El Shaaria","Atatba"}));
         }
    }//GEN-LAST:event_jComboBoxSelectLineActionPerformed

    private void jComboBoxSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSourceActionPerformed

    private void jComboBoxyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxyearActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongIDTicket.setVisible(false);
        jPanelNotAllowed.setVisible(false);
        
        if(!jTextFieldPassenger.getText().equals("") && !jTextFieldIDTicket.getText().equals("") && !jTextFieldIDTicket.getText().equals("") && !jTextFieldPhoneNo.getText().equals("") && !jTextFieldemail.getText().equals(""))
        {
            Validation v = new Validation();
            if(v.checkID(jTextFieldID.getText())){
                    if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                        if(v.checkName(jTextFieldPassenger.getText())){
                            if(v.checkID(jTextFieldIDTicket.getText())){
                                if(v.checkEmail(jTextFieldemail.getText())){
                                    // Name & ID & PhoneNo & Email &Source & distination & t.ID_Train & ID_Ticket
                                   Ticket t = new Ticket();
                                   if(!t.DublicateIDTicket(Integer.parseInt(jTextFieldIDTicket.getText()))){
                                        t.SetName(jTextFieldPassenger.getText());
                                        t.SetID(Integer.parseInt(jTextFieldID.getText()));
                                        t.SetPhoneNo(jTextFieldPhoneNo.getText());
                                        t.SetEmail(jTextFieldemail.getText());
                                        t.SetIDTicket(Integer.parseInt(jTextFieldIDTicket.getText()));

                                        t.SetLine(jComboBoxSelectLine.getSelectedItem().toString());
                                        t.SelectSource(jComboBoxSource.getSelectedItem().toString());
                                        t.SelectDistantion(jComboBoxDistination.getSelectedItem().toString());
                                        jTextFieldPrice.setText(String.valueOf(t.PriceOFTicket(jComboBoxSelectLine.getSelectedItem().toString(),jComboBoxSource.getSelectedItem().toString(), jComboBoxDistination.getSelectedItem().toString())));
                                        t.SetPrice(Integer.parseInt(jTextFieldPrice.getText()));
                                        String date = jComboBoxyear.getSelectedItem().toString()+"#"+jComboBoxmonth.getSelectedItem().toString()+"#"+jComboBoxday.getSelectedItem().toString()
                                                +"#"+jComboBoxHour.getSelectedItem().toString()+"#"+jComboBoxminute.getSelectedItem().toString()+"#";
                                        t.SetDate(date);

                                         if(t.ServeTicket()){
                                             jLabelSuccessOrFail.setText("Added Successufully ... ! :) ");
                                             ResetPanel();
                                         }
                                         else{
                                                jLabelSuccessOrFail.setText("Failed To Insert ...! :(");
                                                JOptionPane.showMessageDialog(null, "Failed To Insert ...!\n Try Again :(");
                                                ResetPanel();
                                            } // Start Elses
                                         }
                                    else{
                                            jLabelSuccessOrFail.setText("Not Allowed New ID Ticket :(");
                                            jPanelNotAllowed.setVisible(true);
                                            JOptionPane.showMessageDialog(null, "Not Allowed ID Ticket , ID Ticket is Reserved...!\n Try Again :(");
                                        }
                                    
                                }
                                else{
                                    JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                    jPanelWrongEmail.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid ID Ticket Try Again :(\nHint: ID Ticket Length should more than 4 .. ;)");
                                jPanelWrongIDTicket.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                            jPanelWrongName.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                        jPanelWrongPhoneNo.setVisible(true);
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Passenger Try Again :(\nHint: ID Passenger Length should more than 4 .. ;)");
                jPanelWrongID.setVisible(true);
            } 
        }
        else
            jLabelSuccessOrFail.setText("Missing Required Fields ... ! Please Fill All Fields (:"); 
    }//GEN-LAST:event_jLabel17MouseClicked
private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ResetPanel();
        jLabelSuccessOrFail.setText("Add Passenger ... !");
        jTextFieldPrice.setText("");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        
        jPanelWrongEmail.setVisible(false);
        jPanelWrongID.setVisible(false);
        jPanelWrongName.setVisible(false);
        jPanelWrongPhoneNo.setVisible(false);
        jPanelWrongIDTicket.setVisible(false);
        
        if(!jTextFieldPassenger.getText().equals("") && !jTextFieldIDTicket.getText().equals("") && !jTextFieldIDTicket.getText().equals("") && !jTextFieldPhoneNo.getText().equals("") && !jTextFieldemail.getText().equals(""))
        {
            Validation v = new Validation();
            if(v.checkID(jTextFieldID.getText())){
                    if(v.checkPhoneNo(jTextFieldPhoneNo.getText())){
                        if(v.checkName(jTextFieldPassenger.getText())){
                            if(v.checkID(jTextFieldIDTicket.getText())){
                                if(v.checkEmail(jTextFieldemail.getText())){
                                    // Name & ID & PhoneNo & Email &Source & distination & t.ID_Train & ID_Ticket
                                   Ticket t = new Ticket();
                                   if(!t.DublicateIDTicket(Integer.parseInt(jTextFieldIDTicket.getText()))){
                                        t.SetName(jTextFieldPassenger.getText());
                                        t.SetID(Integer.parseInt(jTextFieldID.getText()));
                                        t.SetPhoneNo(jTextFieldPhoneNo.getText());
                                        t.SetEmail(jTextFieldemail.getText());
                                        t.SetIDTicket(Integer.parseInt(jTextFieldIDTicket.getText()));

                                        t.SetLine(jComboBoxSelectLine.getSelectedItem().toString());
                                        t.SelectSource(jComboBoxSource.getSelectedItem().toString());
                                        t.SelectDistantion(jComboBoxDistination.getSelectedItem().toString());
                                        jTextFieldPrice.setText(String.valueOf(t.PriceOFTicket(jComboBoxSelectLine.getSelectedItem().toString(),jComboBoxSource.getSelectedItem().toString(), jComboBoxDistination.getSelectedItem().toString())));
                                        t.SetPrice(Integer.parseInt(jTextFieldPrice.getText()));
                                        String date = jComboBoxyear.getSelectedItem().toString()+"#"+jComboBoxmonth.getSelectedItem().toString()+"#"+jComboBoxday.getSelectedItem().toString()
                                                +"#"+jComboBoxHour.getSelectedItem().toString()+"#"+jComboBoxminute.getSelectedItem().toString()+"#";
                                        t.SetDate(date);

                                         if(t.ServeTicket()){
                                             //    public Mail(String To , String Cc , String subject , String body)
                                              Mail m = new Mail();
                                              m.setToEmail(jTextFieldemail.getText());
                                              m.setCcEmail("");
                                              m.setSubject("company reservation employee");
                                              m.setEmailbody("company reservation employee \nYour ID Ticket is  ("+jTextFieldIDTicket.getText()+")  Your ID is ("+jTextFieldID.getText()
                                                              +")   & your Line is ["+jComboBoxSelectLine.getSelectedItem().toString()+"]  & Your Station From ["+jComboBoxSource.getSelectedItem().toString()
                                                              +"]  To ["+jComboBoxDistination.getSelectedItem().toString()+"]  And The Cost is "+String.valueOf(t.PriceOFTicket(jComboBoxSelectLine.getSelectedItem().toString(),jComboBoxSource.getSelectedItem().toString(), jComboBoxDistination.getSelectedItem().toString()))
                                                      +"$ \nAnd Date is :  "+jComboBoxyear.getSelectedItem().toString()+"/"+jComboBoxmonth.getSelectedItem().toString()+"/"+jComboBoxday.getSelectedItem().toString()+"   |    "+jComboBoxHour.getSelectedItem().toString()+":"+jComboBoxminute.getSelectedItem().toString()
                                              +"\n");
                                              try {
                                                  
                                                  m.generateAndSentMessage();
                                                  jLabelSuccessOrFail.setText("Your message has been sent & Added Successufully  ...! :)");
                                                  ResetPanel();
                                              } catch (MessagingException ex) {
                                                  jLabelSuccessOrFail.setText("Your Message hasn't been delivered & Failed To Insert ... ! :(");
                                                  Logger.getLogger(ServeTicket.class.getName()).log(Level.SEVERE, null, ex);
                                              }
                                             ResetPanel();
                                         }
                                        else{
                                                 jLabelSuccessOrFail.setText("Failed To Insert ...! :(");
                                                 JOptionPane.showMessageDialog(null, "Failed To Insert ...!\n Try Again :(");
                                                 ResetPanel();
                                             } // Start Elses
                                         }
                                    else{
                                            jLabelSuccessOrFail.setText("Not Allowed New ID Ticket :(");
                                            jPanelNotAllowed.setVisible(true);
                                            JOptionPane.showMessageDialog(null, "Not Allowed ID Ticket , ID Ticket is Reserved...!\n Try Again :(");
                                    }
                                 }
                                else{
                                    JOptionPane.showMessageDialog(null, "Not valid Input for Email Try Again :(");
                                    jPanelWrongEmail.setVisible(true);
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Not valid ID Ticket Try Again :(\nHint: ID Ticket Length should more than 4 .. ;)");
                                jPanelWrongIDTicket.setVisible(true);
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Not valid Name Try Again :(");
                            jPanelWrongName.setVisible(true);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Phone No Try Again :(\nHint: Phone No should  equal 11 numbers if it mobile\n or more than 8 with Code of Governorate if it Tel  .. ;)");
                        jPanelWrongPhoneNo.setVisible(true);
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Passenger Try Again :(\nHint: ID Passenger Length should more than 4 .. ;)");
                jPanelWrongID.setVisible(true);
            }
            
            
        }
        else
                jLabelSuccessOrFail.setText("Missing required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
        setColor(jPanelProcess);
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        // TODO add your handling code here:
        getColor(jPanelProcess);
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        setColor(jPanelMail);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        getColor(jPanelMail);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        setColor(jPanelReset);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        getColor(jPanelReset);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jComboBoxDistinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDistinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDistinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDistination;
    private javax.swing.JComboBox<String> jComboBoxHour;
    private javax.swing.JComboBox<String> jComboBoxSelectLine;
    private javax.swing.JComboBox<String> jComboBoxSource;
    private javax.swing.JComboBox<String> jComboBoxday;
    private javax.swing.JComboBox<String> jComboBoxminute;
    private javax.swing.JComboBox<String> jComboBoxmonth;
    private javax.swing.JComboBox<String> jComboBoxyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JLabel jLabelWrongEmail;
    private javax.swing.JLabel jLabelWrongID;
    private javax.swing.JLabel jLabelWrongID1;
    private javax.swing.JLabel jLabelWrongIDTicket;
    private javax.swing.JLabel jLabelWrongName;
    private javax.swing.JLabel jLabelWrongPhoneNo;
    private javax.swing.JPanel jPanelMail;
    private javax.swing.JPanel jPanelNotAllowed;
    private javax.swing.JPanel jPanelProcess;
    private javax.swing.JPanel jPanelReset;
    private javax.swing.JPanel jPanelWrongEmail;
    private javax.swing.JPanel jPanelWrongID;
    private javax.swing.JPanel jPanelWrongIDTicket;
    private javax.swing.JPanel jPanelWrongName;
    private javax.swing.JPanel jPanelWrongPhoneNo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDTicket;
    private javax.swing.JTextField jTextFieldPassenger;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldemail;
    // End of variables declaration//GEN-END:variables
}
